version: '3'
services:
  balek-coopilot:
    image: "balek-coopilot-standalone-builder:release"
    build:
      context: "../.."
      dockerfile: "builds/standalone/Dockerfile"
    ports:
      - "443:8080"
    volumes:
      - ./webroot-UNFIPricer:/balek/builds/standalone/buildScripts/UNFIPricer/webroot
      - ./webroot-tabImporter:/balek/builds/standalone/buildScripts/tabImporter/webroot